---
title: "Week Two Unit2 Part One"
author: "Weijia Chen"
date: "22 September 2014"
output: html_document
---

```{r, results='hide', echo=FALSE}
options(scipen = 1)
```

###Introduction

####Definition of Random Process

In a random process we know what outcomes could happen, but we don't know which particular outcome will happen.

Examples of random processes: coin tosses, die rolls, shuffle mode on music player, the stock market

Probability:

$P(A)$ = Probability of event $A$

####Rules for $P(A)$

$0 \leq P(A) \leq 1$

####Law of large numbers

Law of large numbers states that as more observations are collected, the proportion of occurrences with a particular outcome converges to the probability of that outcome.

###Disjoint Events + General Addition Rule

####Disjoint events (mutually exclusive)

1. **_Disjoint (mutually exclusive) events_** cannot happen at the same time. Examples: 
+ The outcome of a single coin toss cannot be a head and a tail;
+ A student cann't both fail and pass a class
+ A single card drawn from a deck cannot be an ace and a queen.

$P(A \ \& \ B) = 0$. It means that the event A and B don't join. 

$P(A \ or \ B) = P(A) + P(B)$

2. **_Non-disjoint_** events can happen at the same time. Examples:
+ A student can get an A in Stats and A in Econ in the same semester.

$P(A \ \& \ B) \neq 0$. It means that the probability of event A and B happening at the same time is non-zero.

$P(A \ or \ B) = P(A) + P(B) - P(A \ and \ B)$

####Sample Space

A sample space is a collection of all possible outcomes of a trial.

####Probability distributions

A **_probability distribution_** lists all possible outcomes in the sample space, and the probabilities with which they occur.

#####Rules of probability distribution
1. The events listed must be disjoint
2. Each probability must be between 0 and 1
3. The sum of the probabilities must equal to 1

####Complementary events

Complementary events are two mutually exclusive events whose probabilities that add up to 1.

#####Disjoint VS Complementary

+ Two disjoint outcomes **_are not necessarily_** add up to 1. For example, dice rolls, dice one and dice two are disjoint, but P(dice one) + P(dice two) = 1/6 + 1/6 = 1/3. If there are more than 2 outcomes in the sample space, two disjoint outcomes won't add up to 1.
+ Complementary is defined for two events, therefore, two complementary event outcomes always add up to 1. For eaxmple: dice rolls, dice one and dice others (2 to 6) are complementary events, (grouped event 2 to 6 together), P(dice one) + P(dice not one) = 1.
+ Complementary events must be disjoint events, however, disjoint events are not necessarily always complementary events.

###Independence
####Independent events

Two processes are **_independent_** if knowing the outcome of one provides no useful information about the outcome of the other.

#####General Rules for checking independence

$P(A \ | \ B) = P(A)$, Then A and B are independent.

**_B means given_**.

####Assessing Independence

If A and B are independent, $P(A \ and \ B) = P(A) * P(B)$.

####Multiplication rule for independent events

If $A_{1}, A_{2}, ... A_{k}$ are independent, $P(A_{1} \ and \ P_{2} \ and ... P_{k}) = P(1) * P(2) * ... * P(k)$ 

###Disjoint VS Independent

In fact, there is no meanings to compare these two terminology. 

Disjoint discusses about one process which includes two events, A and B. Events A and B are disjoint means that they cannot happen at the **_same time_** (one process, e.g. flip coin, head and tail cannot happen at one process filp).
$P(A \ and \ B) = 0$

Independent discusses the conditions about A and B, this mean that there are at least two processes. First, process the outcome of event A. Then, looking the outcomes of event B which is affected or not by event A. It discusses the conditional situaitons. $P(A \ | \ B) = P(A)$
